# Be sure to restart your server when you modify this file.

# Your secret_key_base is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

shared:
  # The minimum number of offices in your floorplan. Offices CAN NOT SHRINK, so
  # start with a conservative estimate of office size. You can always add offices.
  # Floorplan sizes currently range between 15 and 66; multiple floors will be created
  # if num_offices is greater than 66.
  # Note that users can sign onto qube and interact fully without an office
  # (this may be a good option for contractors, investors, etc).
  num_offices: 25
  # Zoom's API key and secret are available at https://developer.zoom.us/me/#api
  # You must sign up for a Pro Account with at least one user for API access.
  zoom_api_key: 9aaA9AaAAAAa9aAa9999aa
  zoom_api_secret: 9aAAAaAAaaAAAaaa99aAAAaAaAAAAA99aa9a
  # You will need to set up a Slack App for qube to generate a client ID/secret.
  # See README for instructions.
  slack_client_id: '9999999999.999999999999'
  slack_client_secret: 9a9a99a999a9999aa99aa9a9999a999a
  # Find your team ID at https://api.slack.com/methods/team.info/test. Generate a
  # token to test with, and click `Test Method`. The ID will appear in the results.
  slack_team_id: T02LE0A28
  # Sign up for a free OpenWeatherMap API key at https://openweathermap.org/appid.
  open_weather_key: 99a9aa99999a99a9a9a9999aa9a9aa99
  # The email used to send qube (Welcome to qube!, Here's how to make the most of qube,
  # and release notes) emails. This email address does not have to exist (no-reply)
  # as long as the mailer is legitimate (see README for instructions).
  mailer_sender: 'qube@company.com'
  # These configuration options are optimal for most offices. You will probably not
  # want to change these, unless you are developing/testing or know what you're doing.
  min_minutes_between_watch_digests: 30
  watcher_notification_delay_seconds: 30
  watched_notification_delay_seconds: 90
  room_request_expiry_minutes: 2
  max_office_size: 8
  comes_online_notification_delay_minutes: 15

development:
  # This secret_key_base by typing in `rails secret` in your terminal. Use a different secret_key_base
  # for your development, test, and production environments.
  secret_key_base: dac26e2a5fc8ef2412064f93b63c054b7f7c6389a24502ae3e0cfb85acda7ca7f3eb66c19a4037837a4b4827816bc34c145aa513dbb4fd7016e3468067271207
  # Generate a webpush public/private key by opening up the rails console (`rails c`), and typing in
  # `vapid_key = Webpush.generate_key`. Save `vapid_key.public_key` and `vapid_key.private_key` to
  # webpush_public_key and webpush_private_key, respectively. Use different keys for development/production.
  webpush_public_key: AAA9aa9Aa99aAA9aAAaA9AAaa9AAa9AaAaaaAaaaa9aaAA9aaaa_a99AA9AA9a9-9aaa9aAAA9AAAAaaaaaaAaa=
  webpush_private_key: a9aaaA9aA9aaaA9_AAaAaAAaaa99AaAaaAaA999Aaaa=
  # Do not change.
  action_cable_url: "ws://localhost:3000/cable"

test:
  # This secret_key_base by typing in `rails secret` in your terminal. Use a different secret_key_base
  # for your development, test, and production environments.
  secret_key_base: 731b36c2a93842f8f0715403a0b06a9813e2a7b8aff99c2f29974c6c07637a193ccbc16fa49ad3af75050997b3f8cff7e4b85a264f00eb20a7a1daf77987df71

# DO NOT keep production secrets in the repository.
production:
  # Generate a secret_key_base by typing in `rails secret` in your terminal. This is your most important secret_key_base - make sure it is not
  # committed to a repository, and different from your development/test secret_key_bases.
  secret_key_base: 731b36c2a93842f8f0715403a0b06a9813e2a7b8aff99c2f29974c6c07637a193ccbc16fa49ad3af75050997b3f8cff7e4b85a264f00eb20a7a1daf77987df71
  # Generate a webpush public/private key by opening up the rails console (`rails c`), and typing in
  # `vapid_key = Webpush.generate_key`. Save `vapid_key.public_key` and `vapid_key.private_key` to
  # webpush_public_key and webpush_private_key, respectively. Use different keys for development/production.
  webpush_public_key: AAA9aa9Aa99aAA9aAAaA9AAaa9AAa9AaAaaaAaaaa9aaAA9aaaa_a99AA9AA9a9-9aaa9aAAA9AAAAaaaaaaAaa=
  webpush_private_key: a9aaaA9aA9aaaA9_AAaAaAAaaa99AaAaaAaA999Aaaa=
  # Update to your URL
  action_cable_url: "wss://localhost:3000/cable"
